### ISSUE TITLE
Problem with Laravel 9

### ISSUE THREAD

**Issue by sajaddp** [paul-thebaud/phpunitgen-core#17]
Hi
When I tried to install the package on fresh Laravel 9, The following error occurred:
```
 Problem 1
    - phpunitgen/console[2.0.0-alpha1, ..., 2.0.0] require league/flysystem ^1.0 -> found league/flysystem[1.0.0-alpha1, ..., 1.x-dev] but the package is fixed to 3.0.3 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires phpunitgen/console ^2.0 -> satisfiable by phpunitgen/console[2.0.0-alpha1, ..., 2.0.0].
 ```

**Comment by paul-thebaud** [comment]
HI @sajaddp,
Sorry, PhpUnitGen does support Laravel 9 for now.
I'll try to release a new version supporting Laravel 9 as soon as possible.

**Comment by paul-thebaud** [comment]
Hi @sajaddp,
PhpUnitGen console 3.0.0 is now released with Laravel 9 support.
Feel free to ask if you need anything else!
