### ISSUE TITLE
Allow PHP version based code generation

### ISSUE THREAD

**Issue by landure** [paul-thebaud/phpunitgen-core#27]
### Subject of the issue

PHP 8.1 alters reflections behavior to be accessible by default. `$property->setAccessible(true);` line is useless (and unwanted) for projects using PHP >= 8.1. See [ReflectionProperty::setAccessible @ PHP documentation](https://www.php.net/manual/en/reflectionproperty.setaccessible.php).

### Your environment

* version of `phpunitgen/core`: 3.1.0
* version of `phpunitgen/console`: 5.0.0

### Steps to reproduce

Generate a test with PhpUnitGen

### Expected behavior

PhpUnitGen configuration file has a `phpVersion` setting. When set to `8.1` and above, `$property->setAccessible(true);`  line isn't present in generated tests.

### Actual behavior

`$property->setAccessible(true);`  is present in generated tests even for projects using recent PHP versions. Psalm raises issues on this.

Thank you for your work.

**Comment by paul-thebaud** [comment]
Hello,

Thank you for this feature request. I'll take a look when I got time.
