### ISSUE TITLE
bug: PHPUnit static methods are called dynamically

### ISSUE THREAD

**Issue by landure** [paul-thebaud/phpunitgen-core#29]
### Subject of the issue

PHPUnit `markTestIncomplete` and `assert*` methods are static. PhpUnitGen generates code calling these methods dynamically.
This raises warning in some code analysis tools ([PHPStan](https://phpstan.org/)).

### Your environment

* version of `phpunitgen/core`: 3.1.0
* version of `phpunitgen/console`: 5.0.0

### Steps to reproduce

Generate a test with PhpUnitGen.

### Expected behavior

The generated code should be:

```php
    public function testSetName(): void
    {
        $expected = '42';
        $property = (new \ReflectionClass(Item::class))
            ->getProperty('name');
        $this->item->setName($expected);
        self::assertSame($expected, $property->getValue($this->item));
    }
```

or

```php
        /* @todo This test is incomplete. */
        self::markTestIncomplete();
```

### Actual behavior

The generated code is:

```php
    public function testSetName(): void
    {
        $expected = '42';
        $property = (new \ReflectionClass(Item::class))
            ->getProperty('name');
        $this->item->setName($expected);
        $this->assertSame($expected, $property->getValue($this->item));
    }
```

or

```php
        /* @todo This test is incomplete. */
        $this->markTestIncomplete();
```

PHPStan raises warning `Dynamic call to static method PHPUnit\Framework\Assert::assertSame().`

**Comment by paul-thebaud** [comment]
@landure, fixed in [`phpunitgen-core@4.0.0`](https://github.com/paul-thebaud/phpunitgen-core/releases/tag/4.0.0) and [`phpunitgen-console@6.0.0`](https://github.com/paul-thebaud/phpunitgen-console/releases/tag/6.0.0).
