### ISSUE TITLE
Add possibility to insert license header

### ISSUE THREAD

**Issue by landure** [paul-thebaud/phpunitgen-core#30]
### Subject of the issue

All my project files contains a license header after the `<?php` tag and before the first line of code. This license header contains the `@author`, `@copyright`, and `@license` annotations.

PhpUnitGen ignore this header and doesn't offer an option to copy it in the test file or insert a new one.

It should allow one action among : 

- copy the existing license header (with an optional additional line `This file is created using PhpUnitGen.`) ;
- insert a custom license header defined in the configuration file (with an option like the `phpDoc` array).

### Your environment

* version of `phpunitgen/core`: 3.1.0
* version of `phpunitgen/console`: 5.0.0

### Expected behavior

The top of a test file should be :

```php
<?php

/**
 * @author Firstname Lastname <firstname.lastname@company.com>
 * @copyright 2023 Company Inc.
 * @license MIT
 *
 * This file is part of Some Project.
 * For the full copyright and license information, please view the LICENSE
 * file distributed with this source code.
 *
 * This file is created using PhpUnitGen.
 */

declare(strict_types=1);

```

### Actual behavior

The top of a test file is :

```php
<?php

declare(strict_types=1);

```

**Comment by paul-thebaud** [comment]
@landure, fixed in [`phpunitgen-core@4.0.0`](https://github.com/paul-thebaud/phpunitgen-core/releases/tag/4.0.0) and [`phpunitgen-console@6.0.0`](https://github.com/paul-thebaud/phpunitgen-console/releases/tag/6.0.0).
